-- FIX FOR PRIVATE DATAREF --
local ffi = require("ffi")
local XPLM = nil
local XPLMlib = "XPLM"
if SYSTEM_ARCHITECTURE == 64 then
	if SYSTEM == "IBM" then
		XPLMlib = "XPLM_64"
	elseif SYSTEM == "LIN" then
		XPLMlib = "Resources/plugins/XPLM_64.so"
	else
		XPLMlib = "Resources/plugins/XPLM.framework/XPLM"
	end
else
	if SYSTEM == "IBM" then
		XPLMlib = "XPLM"
	elseif SYSTEM == "LIN" then
		XPLMlib = "Resources/plugins/XPLM.so"
	else
		XPLMlib = "Resources/plugins/XPLM.framework/XPLM"
	end
end
XPLM = ffi.load(XPLMlib)
ffi.cdef("typedef void * XPLMDataRef;")
ffi.cdef("XPLMDataRef XPLMFindDataRef(const char * inDataRefName);")
ffi.cdef("int XPLMGetDatai(XPLMDataRef inDataRef);")
ffi.cdef("void XPLMSetDatai(XPLMDataRef inDataRef, int inValue);")
ffi.cdef("float XPLMGetDataf(XPLMDataRef inDataRef);")
ffi.cdef("void XPLMSetDataf(XPLMDataRef inDataRef, float inValue);")
ffi.cdef("double XPLMGetDatad(XPLMDataRef inDataRef);")
ffi.cdef("void XPLMSetDatad(XPLMDataRef inDataRef, double inValue);")

function findDataref(drName)
    return XPLM.XPLMFindDataRef(drName)
end
function setDatai(handle, value)
    XPLM.XPLMSetDatai(handle, value)
end

function getDatai(handle)
    return XPLM.XPLMGetDatai(handle)
end

function setDataf(handle, value)
    XPLM.XPLMSetDataf(handle, value)
end

function getDataf(handle)
    return XPLM.XPLMGetDataf(handle)
end

function setDatad(handle, value)
    XPLM.XPLMSetDatad(handle, value)
end

function getDatad(handle)
    return XPLM.XPLMGetDatad(handle)
end

-- csm = findDataref("sim/private/controls/caps/use_csm")
-- setDataf(csm, 0.000000)
-- sp = findDataref("sim/private/controls/perf/disable_shadow_prep")
-- setDataf(sp, 0.000000)
-- LOD_bias_rat = findDataref("sim/private/controls/reno/LOD_bias_rat")
-- setDataf(LOD_bias_rat, 1.3)
-- fade_rat = findDataref("sim/private/controls/terrain/fade_start_rat")
-- setDataf(fade_rat, 1.0)
--fix bad mountains
-- set("sim/private/controls/skyc/max_dsf_vis_ever", 150000)
-- set("sim/private/controls/skyc/min_dsf_vis_ever", 115000)

-- set( "sim/private/controls/skyc/max_shadow_angle",-89)
-- set( "sim/private/controls/skyc/min_shadow_angle",-90)
---

--- JOY SETTINGS ---

-- if PLANE_ICAO == "DC6" then

	-- clear_all_axis_assignments()
	-- set_axis_assignment( 25, "flaps", "normal" )
	-- set_axis_assignment( 50, "elev trim", "normal" )
	-- set_axis_assignment( 75, "pitch", "normal" )
	-- set_axis_assignment( 76, "roll", "normal" )
	-- set_axis_assignment( 78, "prop", "reverse" )
	-- set_axis_assignment( 79, "throttle", "normal" )
	-- set_axis_assignment( 100, "right toe brake", "normal" )
	-- set_axis_assignment( 101, "left toe brake", "normal" )
	-- set_axis_assignment( 102, "yaw", "normal" )
	-- set_axis_assignment( 126, "nosewheel tiller", "normal" )

	-- clear_all_button_assignments()
	-- set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	-- set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	-- set_button_assignment( (0*40) + 4, "PMDG_DC6/autopilot/gyropilot_toggle" )
	-- set_button_assignment( (0*40) + 5, "PMDG_DC6/autopilot/mechanical_disconnect_toggle" )
	-- set_button_assignment( (0*40) + 6, "PMDG_DC6/autopilot/altitude_control_toggle" )
	-- set_button_assignment( (0*40) + 8, "PMDG_DC6/autopilot/pitch_wheel_back" )
	-- set_button_assignment( (0*40) + 9, "PMDG_DC6/autopilot/pitch_wheel_fwd" )
	-- set_button_assignment( (0*40) + 10, "PMDG_DC6/autopilot/mode_localizer" )
	-- set_button_assignment( (0*40) + 11, "PMDG_DC6/autopilot/mode_approach" )
	-- set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	-- set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	-- set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	-- set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	-- set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	-- set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	-- set_button_assignment( (12*40) + 4, "PMDG_DC6/autopilot/turn_knob_center" )
	-- set_button_assignment( (12*40) + 5, "PMDG_DC6/autopilot/mode_gyropilot" )
	-- set_button_assignment( (12*40) + 6, "sim/radios/obs1_down" )
	-- set_button_assignment( (12*40) + 7, "sim/radios/obs1_up" )
	-- set_button_assignment( (12*40) + 11, "PMDG_DC6/autopilot/turn_knob_left" )
	-- set_button_assignment( (12*40) + 12, "PMDG_DC6/autopilot/turn_knob_right" )
	-- set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	-- set_button_assignment( (12*40) + 15, "sim/radios/stby_nav1_coarse_up" )
	-- set_button_assignment( (12*40) + 16, "sim/radios/stby_nav1_coarse_down" )
	-- set_button_assignment( (12*40) + 17, "sim/radios/stby_nav1_fine_up" )
	-- set_button_assignment( (12*40) + 18, "sim/radios/stby_nav1_fine_down" )
	-- set_button_assignment( (12*40) + 20, "sim/engines/thrust_reverse_hold" )
	-- set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	-- set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	-- set_button_assignment( (12*40) + 25, "sim/GPS/g430n1_chapter_up" )
	-- set_button_assignment( (12*40) + 27, "sim/GPS/g430n1_page_up" )
	-- set_button_assignment( (12*40) + 29, "sim/GPS/g430n1_chapter_dn" )
	-- set_button_assignment( (12*40) + 31, "sim/GPS/g430n1_page_dn" )
	-- set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	-- set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	-- set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	-- set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	-- set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	-- set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	-- set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	-- set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	-- set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	-- set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	-- set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- -- setting nullzone, sensitivity and augment
	-- set( "sim/joystick/joystick_pitch_nullzone",      0.080 )
	-- set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	-- set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	-- set( "sim/joystick/joystick_pitch_sensitivity",   1.000 )
	-- set( "sim/joystick/joystick_roll_sensitivity",    0.000 )
	-- set( "sim/joystick/joystick_heading_sensitivity", 0.400 )
	-- set( "sim/joystick/joystick_pitch_augment",       0.000 )
	-- set( "sim/joystick/joystick_roll_augment",        0.000 )
	-- set( "sim/joystick/joystick_heading_augment",     0.000 )

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

	-- -- PLANE_ICAO == "DC6"
	-- -- PLANE_TAILNUMBER == "N6PM"
	-- -- AIRCRAFT_FILENAME == "DC-6A.acf"
-- end


if PLANE_ICAO == "T210" then

	clear_all_axis_assignments()
	set_axis_assignment( 25, "flaps", "normal" )
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "mixture", "reverse" )
	set_axis_assignment( 78, "prop", "reverse" )
	set_axis_assignment( 79, "throttle", "normal" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 4, "sim/autopilot/altitude_up" )
	set_button_assignment( (0*40) + 5, "sim/autopilot/altitude_down" )
	set_button_assignment( (0*40) + 6, "sim/autopilot/altitude_arm" )
	set_button_assignment( (0*40) + 7, "sim/autopilot/vertical_speed_pre_sel" )
	set_button_assignment( (0*40) + 8, "sim/autopilot/vertical_speed_up" )
	set_button_assignment( (0*40) + 9, "sim/autopilot/vertical_speed_down" )
	set_button_assignment( (0*40) + 10, "sim/autopilot/NAV" )
	set_button_assignment( (0*40) + 11, "sim/autopilot/approach" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 4, "sim/autopilot/altitude_hold" )
	set_button_assignment( (12*40) + 5, "sim/autopilot/heading" )
	set_button_assignment( (12*40) + 6, "sim/radios/obs1_down" )
	set_button_assignment( (12*40) + 7, "sim/radios/obs1_up" )
	set_button_assignment( (12*40) + 11, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 12, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/stby_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/stby_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/stby_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/stby_nav1_fine_down" )
	set_button_assignment( (12*40) + 20, "sim/engines/thrust_reverse_hold" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/GPS/g430n1_chapter_up" )
	set_button_assignment( (12*40) + 27, "sim/GPS/g430n1_page_up" )
	set_button_assignment( (12*40) + 29, "sim/GPS/g430n1_chapter_dn" )
	set_button_assignment( (12*40) + 31, "sim/GPS/g430n1_page_dn" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.080 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   1.000 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.000 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.400 )
	set( "sim/joystick/joystick_pitch_augment",       0.000 )
	set( "sim/joystick/joystick_roll_augment",        0.000 )
	set( "sim/joystick/joystick_heading_augment",     0.000 )

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

	-- PLANE_ICAO == "T210"
	-- PLANE_TAILNUMBER == "N3888Y"
	-- AIRCRAFT_FILENAME == "Car_Centurion.acf"

end

if PLANE_ICAO == "B733" then
	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
	-- --     FlyWithLua: The initial assignments are stored in this file.     -- --
	-- -- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
	-- --     FlyWithLua: The initial assignments are stored in this file.     -- --
	-- -- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "throttle 2", "normal" )
	set_axis_assignment( 78, "throttle 1", "normal" )
	set_axis_assignment( 79, "speedbrakes", "normal" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 4, "ixeg/733/autopilot/ALT_decrease" )
	set_button_assignment( (12*40) + 5, "ixeg/733/autopilot/ALT_increase" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 11, "ixeg/733/ehsi/map_mode_dec_pilot" )
	set_button_assignment( (12*40) + 12, "ixeg/733/ehsi/map_mode_inc_pilot" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/actv_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/actv_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/actv_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/actv_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.550 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.550 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.550 )
	set( "sim/joystick/joystick_pitch_augment",       0.000 )
	set( "sim/joystick/joystick_roll_augment",        0.000 )
	set( "sim/joystick/joystick_heading_augment",     0.000 )
	

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

	-- PLANE_ICAO == "B733"
	-- PLANE_TAILNUMBER == "D-IXEG"
	-- AIRCRAFT_FILENAME == "B733.acf"


end

if PLANE_ICAO == "PA18" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 79, "throttle", "normal" )
	set_axis_assignment( 78, "prop", "reverse" )
	set_axis_assignment( 77, "mixture", "reverse" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/actv_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/actv_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/actv_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/actv_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )
	set_button_assignment( (0*40) + 10, "sim/autopilot/NAV" )
	set_button_assignment( (0*40) + 11, "sim/autopilot/approach" )	
	set_button_assignment( (0*40) + 4, "sim/autopilot/altitude_hold" )
	set_button_assignment( (0*40) + 5, "sim/autopilot/heading" )	
	set_button_assignment( (12*40) + 11, "sim/radios/obs1_down" )
	set_button_assignment( (12*40) + 12, "sim/radios/obs1_up" )	

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.000 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.000 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.000 )
	set( "sim/joystick/joystick_pitch_augment",       1.000 )
	set( "sim/joystick/joystick_roll_augment",        1.000 )
	set( "sim/joystick/joystick_heading_augment",     1.000 )

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --
end

-- PLANE_ICAO == "PA18"
-- PLANE_TAILNUMBER == ""
-- AIRCRAFT_FILENAME == "ASDG_Super_Cub_180HP.acf"
if PLANE_ICAO == "PA18a" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "throttle", "normal" )
	set_axis_assignment( 78, "prop", "reverse" )
	set_axis_assignment( 79, "mixture", "reverse" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 4, "ixeg/733/autopilot/ALT_decrease" )
	set_button_assignment( (12*40) + 5, "ixeg/733/autopilot/ALT_increase" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 11, "ixeg/733/ehsi/map_mode_dec_pilot" )
	set_button_assignment( (12*40) + 12, "ixeg/733/ehsi/map_mode_inc_pilot" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/actv_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/actv_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/actv_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/actv_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.000 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.000 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.000 )
	set( "sim/joystick/joystick_pitch_augment",       1.000 )
	set( "sim/joystick/joystick_roll_augment",        1.000 )
	set( "sim/joystick/joystick_heading_augment",     1.000 )

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

-- PLANE_ICAO == "PA18"
-- PLANE_TAILNUMBER == ""
-- AIRCRAFT_FILENAME == "ASDG_Super_Cub_180HP.acf"
end
if PLANE_ICAO == "PA28" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 79, "throttle", "normal" )
	set_axis_assignment( 78, "prop", "reverse" )
	set_axis_assignment( 77, "mixture", "reverse" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/actv_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/actv_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/actv_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/actv_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )
	set_button_assignment( (0*40) + 10, "sim/autopilot/NAV" )
	set_button_assignment( (0*40) + 11, "sim/autopilot/approach" )	
	set_button_assignment( (0*40) + 4, "sim/autopilot/altitude_hold" )
	set_button_assignment( (0*40) + 5, "sim/autopilot/heading" )	
	set_button_assignment( (12*40) + 11, "sim/radios/obs1_down" )
	set_button_assignment( (12*40) + 12, "sim/radios/obs1_up" )	

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.000 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.000 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.000 )
	set( "sim/joystick/joystick_pitch_augment",       1.000 )
	set( "sim/joystick/joystick_roll_augment",        1.000 )
	set( "sim/joystick/joystick_heading_augment",     1.000 )

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

-- PLANE_ICAO == "PA18"
-- PLANE_TAILNUMBER == ""
-- AIRCRAFT_FILENAME == "ASDG_Super_Cub_180HP.acf"
end

if PLANE_ICAO == "DC3" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "throttle 2", "normal" )
	set_axis_assignment( 78, "throttle 1", "normal" )
	set_axis_assignment( 79, "speedbrakes", "normal" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 4, "sim/autopilot/NAV" )
	set_button_assignment( (0*40) + 5, "sim/autopilot/approach" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 10, "sim/autopilot/altitude_hold" )
	set_button_assignment( (0*40) + 11, "sim/autopilot/heading" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/actv_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/actv_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/actv_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/actv_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.550 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.550 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.550 )
	set( "sim/joystick/joystick_pitch_augment",       0.000 )
	set( "sim/joystick/joystick_roll_augment",        0.000 )
	set( "sim/joystick/joystick_heading_augment",     0.000 )
end

if PLANE_ICAO == "EA50" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "throttle 2", "normal" )
	set_axis_assignment( 78, "throttle 1", "normal" )
	set_axis_assignment( 79, "speedbrakes", "normal" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	--set_button_assignment( (12*40) + 4, "ixeg/733/autopilot/ALT_decrease" )
	--set_button_assignment( (12*40) + 5, "ixeg/733/autopilot/ALT_increase" )
	set_button_assignment( (12*40) + 4, "sim/autopilot/altitude_up" )
	set_button_assignment( (12*40) + 5, "sim/autopilot/altitude_down" )	
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	--set_button_assignment( (12*40) + 11, "ixeg/733/ehsi/map_mode_dec_pilot" )
	--set_button_assignment( (12*40) + 12, "ixeg/733/ehsi/map_mode_inc_pilot" )
	set_button_assignment( (12*40) + 11, "sim/radios/obs1_down" )
	set_button_assignment( (12*40) + 12, "sim/radios/obs1_up" )	
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/stby_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/stby_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/stby_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/stby_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   0.550 )
	set( "sim/joystick/joystick_roll_sensitivity",    0.550 )
	set( "sim/joystick/joystick_heading_sensitivity", 0.550 )
	set( "sim/joystick/joystick_pitch_augment",       0.000 )
	set( "sim/joystick/joystick_roll_augment",        0.000 )
	set( "sim/joystick/joystick_heading_augment",     0.000 )

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

	-- PLANE_ICAO == "EA50"
	-- PLANE_TAILNUMBER == "N31SL"
	-- AIRCRAFT_FILENAME == "Eclipse_NG.acf"
end

if PLANE_ICAO == "PIPA" then
	clear_all_axis_assignments()
	set_axis_assignment( 50, "elev trim", "normal" )
	set_axis_assignment( 75, "pitch", "normal" )
	set_axis_assignment( 76, "roll", "normal" )
	set_axis_assignment( 77, "mixture", "reverse" )
	set_axis_assignment( 78, "prop", "reverse" )
	set_axis_assignment( 79, "throttle", "normal" )
	set_axis_assignment( 100, "right toe brake", "normal" )
	set_axis_assignment( 101, "left toe brake", "normal" )
	set_axis_assignment( 102, "yaw", "normal" )
	set_axis_assignment( 126, "nosewheel tiller", "normal" )

	clear_all_button_assignments()
	set_button_assignment( (6*40) + 10, "0" )
	set_button_assignment( (6*40) + 11, "0" )
	set_button_assignment( (6*40) + 12, "0" )
	set_button_assignment( (6*40) + 13, "0" )
	set_button_assignment( (6*40) + 14, "0" )
	set_button_assignment( (6*40) + 15, "0" )
	set_button_assignment( (6*40) + 16, "0" )
	set_button_assignment( (6*40) + 17, "0" )
	set_button_assignment( (6*40) + 18, "0" )
	set_button_assignment( (6*40) + 19, "0" )
	set_button_assignment( (6*40) + 20, "0" )
	set_button_assignment( (6*40) + 21, "0" )
	set_button_assignment( (6*40) + 22, "0" )
	set_button_assignment( (6*40) + 23, "0" )
	set_button_assignment( (6*40) + 24, "0" )
	set_button_assignment( (6*40) + 25, "0" )
	set_button_assignment( (6*40) + 26, "0" )
	set_button_assignment( (6*40) + 27, "0" )
	set_button_assignment( (6*40) + 28, "0" )
	set_button_assignment( (6*40) + 29, "0" )
	set_button_assignment( (6*40) + 30, "0" )
	set_button_assignment( (6*40) + 31, "0" )
	set_button_assignment( (6*40) + 32, "0" )
	set_button_assignment( (6*40) + 33, "0" )
	set_button_assignment( (6*40) + 34, "0" )
	set_button_assignment( (6*40) + 35, "0" )
	set_button_assignment( (6*40) + 36, "0" )
	set_button_assignment( (6*40) + 37, "0" )
	set_button_assignment( (6*40) + 38, "0" )
	set_button_assignment( (6*40) + 39, "0" )
	set_button_assignment( (7*40) + 0, "0" )
	set_button_assignment( (7*40) + 1, "0" )
	set_button_assignment( (7*40) + 2, "0" )
	set_button_assignment( (7*40) + 3, "0" )
	set_button_assignment( (7*40) + 4, "0" )
	set_button_assignment( (7*40) + 5, "0" )
	set_button_assignment( (7*40) + 6, "0" )
	set_button_assignment( (7*40) + 7, "0" )
	set_button_assignment( (7*40) + 8, "0" )
	set_button_assignment( (7*40) + 9, "0" )
	set_button_assignment( (7*40) + 10, "0" )
	set_button_assignment( (7*40) + 11, "0" )
	set_button_assignment( (7*40) + 12, "0" )
	set_button_assignment( (7*40) + 13, "0" )
	set_button_assignment( (7*40) + 14, "0" )
	set_button_assignment( (7*40) + 15, "0" )
	set_button_assignment( (7*40) + 16, "0" )
	set_button_assignment( (7*40) + 17, "0" )
	set_button_assignment( (7*40) + 18, "0" )
	set_button_assignment( (7*40) + 19, "0" )
	set_button_assignment( (7*40) + 20, "0" )
	set_button_assignment( (7*40) + 21, "0" )
	set_button_assignment( (7*40) + 22, "0" )
	set_button_assignment( (7*40) + 23, "0" )
	set_button_assignment( (7*40) + 24, "0" )
	set_button_assignment( (7*40) + 25, "0" )
	set_button_assignment( (7*40) + 26, "0" )
	set_button_assignment( (7*40) + 27, "0" )
	set_button_assignment( (7*40) + 28, "0" )
	set_button_assignment( (7*40) + 29, "0" )
	set_button_assignment( (7*40) + 30, "0" )
	set_button_assignment( (7*40) + 31, "0" )
	set_button_assignment( (7*40) + 32, "0" )
	set_button_assignment( (7*40) + 33, "0" )
	set_button_assignment( (7*40) + 34, "0" )
	set_button_assignment( (7*40) + 35, "0" )
	set_button_assignment( (7*40) + 36, "0" )
	set_button_assignment( (7*40) + 37, "0" )
	set_button_assignment( (7*40) + 38, "0" )
	set_button_assignment( (7*40) + 39, "0" )
	set_button_assignment( (8*40) + 0, "0" )
	set_button_assignment( (8*40) + 1, "0" )
	set_button_assignment( (8*40) + 2, "0" )
	set_button_assignment( (8*40) + 3, "0" )
	set_button_assignment( (8*40) + 4, "0" )
	set_button_assignment( (8*40) + 5, "0" )
	set_button_assignment( (8*40) + 6, "0" )
	set_button_assignment( (8*40) + 7, "0" )
	set_button_assignment( (8*40) + 8, "0" )
	set_button_assignment( (8*40) + 9, "0" )
	set_button_assignment( (8*40) + 10, "0" )
	set_button_assignment( (8*40) + 11, "0" )
	set_button_assignment( (8*40) + 12, "0" )
	set_button_assignment( (8*40) + 13, "0" )
	set_button_assignment( (8*40) + 14, "0" )
	set_button_assignment( (8*40) + 15, "0" )
	set_button_assignment( (8*40) + 16, "0" )
	set_button_assignment( (8*40) + 17, "0" )
	set_button_assignment( (8*40) + 18, "0" )
	set_button_assignment( (8*40) + 19, "0" )
	set_button_assignment( (8*40) + 20, "0" )
	set_button_assignment( (8*40) + 21, "0" )
	set_button_assignment( (8*40) + 22, "0" )
	set_button_assignment( (8*40) + 23, "0" )
	set_button_assignment( (8*40) + 24, "0" )
	set_button_assignment( (8*40) + 25, "0" )
	set_button_assignment( (8*40) + 26, "0" )
	set_button_assignment( (8*40) + 27, "0" )
	set_button_assignment( (8*40) + 28, "0" )
	set_button_assignment( (8*40) + 29, "0" )
	set_button_assignment( (8*40) + 30, "0" )
	set_button_assignment( (8*40) + 31, "0" )
	set_button_assignment( (8*40) + 32, "0" )
	set_button_assignment( (8*40) + 33, "0" )
	set_button_assignment( (8*40) + 34, "0" )
	set_button_assignment( (8*40) + 35, "0" )
	set_button_assignment( (8*40) + 36, "0" )
	set_button_assignment( (8*40) + 37, "0" )
	set_button_assignment( (8*40) + 38, "0" )
	set_button_assignment( (8*40) + 39, "0" )
	set_button_assignment( (9*40) + 0, "0" )
	set_button_assignment( (9*40) + 1, "0" )
	set_button_assignment( (9*40) + 2, "0" )
	set_button_assignment( (9*40) + 3, "0" )
	set_button_assignment( (9*40) + 4, "0" )
	set_button_assignment( (9*40) + 5, "0" )
	set_button_assignment( (9*40) + 6, "0" )
	set_button_assignment( (9*40) + 7, "0" )
	set_button_assignment( (9*40) + 8, "0" )
	set_button_assignment( (9*40) + 9, "0" )
	set_button_assignment( (9*40) + 10, "0" )
	set_button_assignment( (9*40) + 11, "0" )
	set_button_assignment( (9*40) + 12, "0" )
	set_button_assignment( (9*40) + 13, "0" )
	set_button_assignment( (9*40) + 14, "0" )
	set_button_assignment( (9*40) + 15, "0" )
	set_button_assignment( (9*40) + 16, "0" )
	set_button_assignment( (9*40) + 17, "0" )
	set_button_assignment( (9*40) + 18, "0" )
	set_button_assignment( (9*40) + 19, "0" )
	set_button_assignment( (9*40) + 20, "0" )
	set_button_assignment( (9*40) + 21, "0" )
	set_button_assignment( (9*40) + 22, "0" )
	set_button_assignment( (9*40) + 23, "0" )
	set_button_assignment( (9*40) + 24, "0" )
	set_button_assignment( (9*40) + 25, "0" )
	set_button_assignment( (9*40) + 26, "0" )
	set_button_assignment( (9*40) + 27, "0" )
	set_button_assignment( (9*40) + 28, "0" )
	set_button_assignment( (9*40) + 29, "0" )
	set_button_assignment( (9*40) + 30, "0" )
	set_button_assignment( (9*40) + 31, "0" )
	set_button_assignment( (9*40) + 32, "0" )
	set_button_assignment( (9*40) + 33, "0" )
	set_button_assignment( (9*40) + 34, "0" )
	set_button_assignment( (9*40) + 35, "0" )
	set_button_assignment( (9*40) + 36, "0" )
	set_button_assignment( (9*40) + 37, "0" )
	set_button_assignment( (9*40) + 38, "0" )
	set_button_assignment( (9*40) + 39, "0" )
	set_button_assignment( (10*40) + 0, "0" )
	set_button_assignment( (10*40) + 1, "0" )
	set_button_assignment( (10*40) + 2, "0" )
	set_button_assignment( (10*40) + 3, "0" )
	set_button_assignment( (10*40) + 4, "0" )
	set_button_assignment( (10*40) + 5, "0" )
	set_button_assignment( (10*40) + 6, "0" )
	set_button_assignment( (10*40) + 7, "0" )
	set_button_assignment( (10*40) + 8, "0" )
	set_button_assignment( (10*40) + 9, "0" )
	set_button_assignment( (10*40) + 10, "0" )
	set_button_assignment( (10*40) + 11, "0" )
	set_button_assignment( (10*40) + 12, "0" )
	set_button_assignment( (10*40) + 13, "0" )
	set_button_assignment( (10*40) + 14, "0" )
	set_button_assignment( (10*40) + 15, "0" )
	set_button_assignment( (10*40) + 16, "0" )
	set_button_assignment( (10*40) + 17, "0" )
	set_button_assignment( (10*40) + 18, "0" )
	set_button_assignment( (10*40) + 19, "0" )
	set_button_assignment( (10*40) + 20, "0" )
	set_button_assignment( (10*40) + 21, "0" )
	set_button_assignment( (10*40) + 22, "0" )
	set_button_assignment( (10*40) + 23, "0" )
	set_button_assignment( (10*40) + 24, "0" )
	set_button_assignment( (10*40) + 25, "0" )
	set_button_assignment( (10*40) + 26, "0" )
	set_button_assignment( (10*40) + 27, "0" )
	set_button_assignment( (10*40) + 28, "0" )
	set_button_assignment( (10*40) + 29, "0" )
	set_button_assignment( (10*40) + 30, "0" )
	set_button_assignment( (10*40) + 31, "0" )
	set_button_assignment( (10*40) + 32, "0" )
	set_button_assignment( (10*40) + 33, "0" )
	set_button_assignment( (10*40) + 34, "0" )
	set_button_assignment( (10*40) + 35, "0" )
	set_button_assignment( (10*40) + 36, "0" )
	set_button_assignment( (10*40) + 37, "0" )
	set_button_assignment( (10*40) + 38, "0" )
	set_button_assignment( (10*40) + 39, "0" )
	set_button_assignment( (11*40) + 0, "0" )
	set_button_assignment( (11*40) + 1, "0" )
	set_button_assignment( (11*40) + 2, "0" )
	set_button_assignment( (11*40) + 3, "0" )
	set_button_assignment( (11*40) + 4, "0" )
	set_button_assignment( (11*40) + 5, "0" )
	set_button_assignment( (11*40) + 6, "0" )
	set_button_assignment( (11*40) + 7, "0" )
	set_button_assignment( (11*40) + 8, "0" )
	set_button_assignment( (11*40) + 9, "0" )
	set_button_assignment( (11*40) + 10, "0" )
	set_button_assignment( (11*40) + 11, "0" )
	set_button_assignment( (11*40) + 12, "0" )
	set_button_assignment( (11*40) + 13, "0" )
	set_button_assignment( (11*40) + 14, "0" )
	set_button_assignment( (11*40) + 15, "0" )
	set_button_assignment( (11*40) + 16, "0" )
	set_button_assignment( (11*40) + 17, "0" )
	set_button_assignment( (11*40) + 18, "0" )
	set_button_assignment( (11*40) + 19, "0" )
	set_button_assignment( (11*40) + 20, "0" )
	set_button_assignment( (11*40) + 21, "0" )
	set_button_assignment( (11*40) + 22, "0" )
	set_button_assignment( (11*40) + 23, "0" )
	set_button_assignment( (11*40) + 24, "0" )
	set_button_assignment( (11*40) + 25, "0" )
	set_button_assignment( (11*40) + 26, "0" )
	set_button_assignment( (11*40) + 27, "0" )
	set_button_assignment( (11*40) + 28, "0" )
	set_button_assignment( (11*40) + 29, "0" )
	set_button_assignment( (11*40) + 30, "0" )
	set_button_assignment( (11*40) + 31, "0" )
	set_button_assignment( (11*40) + 32, "0" )
	set_button_assignment( (11*40) + 33, "0" )
	set_button_assignment( (11*40) + 34, "0" )
	set_button_assignment( (11*40) + 35, "0" )
	set_button_assignment( (11*40) + 36, "0" )
	set_button_assignment( (11*40) + 37, "0" )
	set_button_assignment( (11*40) + 38, "0" )
	set_button_assignment( (11*40) + 39, "0" )
	set_button_assignment( (12*40) + 0, "0" )
	set_button_assignment( (12*40) + 1, "0" )
	set_button_assignment( (12*40) + 2, "0" )
	set_button_assignment( (12*40) + 3, "0" )
	set_button_assignment( (12*40) + 4, "0" )
	set_button_assignment( (12*40) + 5, "0" )
	set_button_assignment( (12*40) + 6, "0" )
	set_button_assignment( (12*40) + 7, "0" )
	set_button_assignment( (12*40) + 8, "0" )
	set_button_assignment( (12*40) + 9, "0" )
	set_button_assignment( (12*40) + 10, "0" )
	set_button_assignment( (12*40) + 11, "0" )
	set_button_assignment( (12*40) + 12, "0" )
	set_button_assignment( (12*40) + 13, "0" )
	set_button_assignment( (12*40) + 14, "0" )
	set_button_assignment( (12*40) + 15, "0" )
	set_button_assignment( (12*40) + 16, "0" )
	set_button_assignment( (12*40) + 17, "0" )
	set_button_assignment( (12*40) + 18, "0" )
	set_button_assignment( (12*40) + 19, "0" )
	set_button_assignment( (0*40) + 0, "sim/autopilot/servos_toggle" )
	set_button_assignment( (0*40) + 2, "sim/flight_controls/pitch_trim_down" )
	set_button_assignment( (0*40) + 4, "sim/autopilot/altitude_hold" )
	set_button_assignment( (0*40) + 5, "sim/autopilot/heading" )
	set_button_assignment( (0*40) + 8, "sim/flight_controls/flaps_up" )
	set_button_assignment( (0*40) + 9, "sim/flight_controls/flaps_down" )
	set_button_assignment( (0*40) + 10, "sim/autopilot/NAV" )
	set_button_assignment( (0*40) + 11, "sim/autopilot/approach" )
	set_button_assignment( (0*40) + 12, "sim/general/up" )
	set_button_assignment( (0*40) + 16, "sim/general/down" )
	set_button_assignment( (4*40) + 1, "sim/radios/com1_standy_flip" )
	set_button_assignment( (4*40) + 2, "sim/radios/stby_com1_coarse_up" )
	set_button_assignment( (4*40) + 3, "sim/radios/stby_com1_coarse_down" )
	set_button_assignment( (4*40) + 4, "sim/radios/stby_com1_fine_up_833" )
	set_button_assignment( (4*40) + 5, "sim/radios/stby_com1_fine_down_833" )
	set_button_assignment( (4*40) + 6, "sim/engines/thrust_reverse_toggle" )
	set_button_assignment( (12*40) + 0, "sim/operation/contact_atc" )
	set_button_assignment( (12*40) + 4, "sim/autopilot/vertical_speed_down" )
	set_button_assignment( (12*40) + 5, "sim/autopilot/vertical_speed_up" )
	set_button_assignment( (12*40) + 6, "sim/autopilot/heading_down" )
	set_button_assignment( (12*40) + 7, "sim/autopilot/heading_up" )
	set_button_assignment( (12*40) + 11, "sim/radios/obs1_down" )
	set_button_assignment( (12*40) + 12, "sim/radios/obs1_up" )
	set_button_assignment( (12*40) + 14, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (12*40) + 15, "sim/radios/stby_nav1_coarse_up" )
	set_button_assignment( (12*40) + 16, "sim/radios/stby_nav1_coarse_down" )
	set_button_assignment( (12*40) + 17, "sim/radios/stby_nav1_fine_up" )
	set_button_assignment( (12*40) + 18, "sim/radios/stby_nav1_fine_down" )
	set_button_assignment( (12*40) + 22, "sim/audio_panel/transmit_audio_com1" )
	set_button_assignment( (12*40) + 23, "sim/audio_panel/transmit_audio_com2" )
	set_button_assignment( (12*40) + 25, "sim/general/forward" )
	set_button_assignment( (12*40) + 27, "sim/general/right" )
	set_button_assignment( (12*40) + 29, "sim/general/backward" )
	set_button_assignment( (12*40) + 31, "sim/general/left" )
	set_button_assignment( (20*40) + 0, "sim/radios/stby_com2_coarse_down" )
	set_button_assignment( (20*40) + 1, "sim/radios/stby_com2_fine_up" )
	set_button_assignment( (20*40) + 2, "sim/radios/stby_com2_fine_down" )
	set_button_assignment( (20*40) + 3, "sim/radios/stby_com2_coarse_up" )
	set_button_assignment( (20*40) + 4, "sim/radios/nav2_standy_flip" )
	set_button_assignment( (20*40) + 5, "sim/radios/nav1_standy_flip" )
	set_button_assignment( (20*40) + 7, "sim/radios/com2_standy_flip" )
	set_button_assignment( (20*40) + 10, "sim/radios/stby_nav2_coarse_up" )
	set_button_assignment( (20*40) + 12, "sim/radios/stby_nav2_fine_up" )
	set_button_assignment( (20*40) + 14, "sim/radios/stby_nav2_coarse_down" )
	set_button_assignment( (20*40) + 16, "sim/radios/stby_nav2_fine_down" )

	-- setting nullzone, sensitivity and augment
	set( "sim/joystick/joystick_pitch_nullzone",      0.000 )
	set( "sim/joystick/joystick_roll_nullzone",       0.000 )
	set( "sim/joystick/joystick_heading_nullzone",    0.032 )
	set( "sim/joystick/joystick_pitch_sensitivity",   1.000 )
	set( "sim/joystick/joystick_roll_sensitivity",    1.000 )
	set( "sim/joystick/joystick_heading_sensitivity", 1.000 )
	set( "sim/joystick/joystick_pitch_augment",       0.000 )
	set( "sim/joystick/joystick_roll_augment",        0.000 )
	set( "sim/joystick/joystick_heading_augment",     0.000 )

	-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- >8 -- --

	-- PLANE_ICAO == "PIPA"
	-- PLANE_TAILNUMBER == "S5MTP"
	-- AIRCRAFT_FILENAME == "panthera.acf"

end